version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports: 
      - 10080:80
    volumes: 
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - /sessions

  node:
    build: ./node
    image: node-express-dev:1.0
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - 8081:3000

volumes:
  db-store:
